theme: jekyll-theme-architect
title: Srilalitha Veerubhotla /Department of Software Engineering,San Jose State University | San Jose, CA | srilalitha.veerubhotla@sjsu.edu | (913) 850-1811
Description: A Former Data scientist and a Zeal Maker in Data Driven World
